#!/bin/sh

ADD_USER=postgres
ADD_USER_HOME=/var/empty
ADD_USER_SHELL=/bin/bash
ADD_GROUP=postgres

set -x -u -e

/usr/sbin/groupadd --system --force $ADD_GROUP
/usr/sbin/useradd --system --home $ADD_USER_HOME --shell $ADD_USER_SHELL --gid $ADD_GROUP $ADD_USER

chown -R $ADD_USER:$ADD_GROUP /var/log/postgresql/postgresql.log
sed -i s/"daemon"/"$ADD_USER"/ /etc/rc.d/postgresql

if [[ ! -d /srv/db/pgsql ]]; then
	mkdir -p /srv/db/pgsql
	chown $ADD_USER:$ADD_GROUP /srv/db/pgsql
	su - $ADD_USER -c "initdb -D /srv/db/pgsql --encoding=UTF8 --locale=en_US.UTF8"
fi
