#!/bin/bash
#
# /etc/rc.d/zebra: GNU Zebra routing manager

# The process must be configured first.
[ -f /etc/quagga/zebra.conf ] || exit 0

RETVAL=0

case "$1" in
  start)
	echo -n $"Starting zebra "
	/usr/sbin/ip route flush proto zebra
	/usr/sbin/zebra -d -r
	RETVAL=$?
	echo
	;;
  stop)
	echo -n $"Shutting down zebra "
	killall /usr/sbin/zebra
	RETVAL=$?
	echo
	;;
  restart|reload)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $RETVAL
