#!/bin/bash
#
# /etc/rc.d/php-fcgi-fpm: start/stop FastCGI php daemon
#

PHP="/usr/bin/php-cgi-fpm"
OPTIONS="--fpm"
PHP_PID="/var/run/php-fpm.pid"

case $1 in
start)
	$PHP $OPTIONS
	;;
stop)
	kill  `cat $PHP_PID`
	;;
rotate)
	kill -SIGUSR1 `cat $PHP_PID`
	;;
reload)
	kill -SIGUSR2 `cat $PHP_PID`
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart|rotate]"
	;;
esac

# End of file
