#!/bin/sh

ADD_USER=apache
ADD_USER_HOME=/var/empty
ADD_USER_SHELL=/bin/false
ADD_GROUP=apache

set -x -u -e

/usr/sbin/groupadd --system --force $ADD_GROUP
/usr/sbin/useradd --system --home $ADD_USER_HOME --shell $ADD_USER_SHELL --gid $ADD_GROUP $ADD_USER

sed -i s/"User\ daemon"/"User\ $ADD_USER"/  /etc/apache/httpd.conf
sed -i s/"Group\ daemon"/"Group\ $ADD_GROUP"/  /etc/apache/httpd.conf
sed -i s/"User\ daemon"/"User\ $ADD_USER"/  /etc/apache/original/httpd.conf
sed -i s/"Group\ daemon"/"Group\ $ADD_GROUP"/  /etc/apache/original/httpd.conf
